version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
#    command: npm run serve
    command: http-server dist --port 80
    ports:
      - "80:80"

  web:
    # Берем Dockerfile из каталога app
    build:
      context: ./api
      dockerfile: slim.Dockerfile
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"