# Generated by Django 3.2.11 on 2022-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
    ]
